#Tomcat
server:
  tomcat:
          uri-encoding: UTF-8
          max-threads: 1000
          min-spare-threads: 30
    port: 8020
  servlet:
    context-path: /order-system
#Spring
spring:
    profiles:
        active:  dev
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/views/
     # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
# Mybatis配置
mybatis:
    mapperLocations: classpath:mybatis/**/*.xml
    configLocation: classpath:mybatis.xml
# 日志 分支提交
logging:
   path: /home/logs/
   file: ${logging.path}order_system
